USE [Quanlykho]
GO
create database Quanlykho -- tạo database trong thư mục chỉ định

ON PRIMARY
(NAME =N'Quanlykho',FILENAME = N'C:\Quanlykho\Web_Ban_Quan_Ao.mdf',SIZE = 100,MAXSIZE = 2GB,FILEGROWTH=10)
LOG ON
(NAME = N'Quanlykho_Log',FILENAME = N'C:\Quanlykho\Web_Ban_Quan_Ao_Log.ldf',SIZE =200,MAXSIZE = UNLIMITED,FILEGROWTH = 20)
GO

use Quanlykho
go

/* Object:  Table [dbo].[KHACHHANG]    */

CREATE TABLE HANGHOA(
	MAHANGHOA	INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,  --TẠO KHÓA CHÍNH
	TENHANGHOA	NVARCHAR(100) NOT NULL,
	XUATXU	    NVARCHAR(100) NOT NULL,
	DONGIA	    MONEY NOT NULL,
	SOLUONGSANSANG	 INT NULL
 );

 CREATE TABLE NHACUNGCAP(
	MANHACUNGCAP	INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,  --TẠO KHÓA CHÍNH
	TENNHACUNGCAP	NVARCHAR(100) NOT NULL,
	DIACHI			NVARCHAR(100) NOT NULL,
	SĐT				INT NOT NULL
);
 

/* Object:  Table [dbo].[NHAPKHO]    */

CREATE TABLE NHAPKHO(
	MANHAPKHO INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,  --TẠO KHÓA CHÍNH
	NGAYNHAPKHO DATE NOT NULL,
	ID_MAHANGHOA  INT FOREIGN KEY REFERENCES HANGHOA(MAHANGHOA) NOT NULL,--TẠO KHÓA NGOẠI 
	ID_MANHACUNGCAP INT FOREIGN KEY REFERENCES NHACUNGCAP(MANHACUNGCAP) NOT NULL,--TẠO KHÓA NGOẠI 
	SOLUONG INT NOT NULL,
	DONGIA MONEY NOT NULL,
	THANHTIEN MONEY NULL,
);	
 
/* Object:  Table [dbo].[XUATKHO]    */

CREATE TABLE XUATKHO(
	MAXUATKHO INT IDENTITY(1,1)  PRIMARY KEY NOT NULL,  --TẠO KHÓA CHÍNH
	NGAYXUATKHO DATE NOT NULL,
	ID_MAHANGHOA  INT FOREIGN KEY REFERENCES HANGHOA(MAHANGHOA) NOT NULL,--TẠO KHÓA NGOẠI 
	SOLUONG INT NOT NULL,
	DONGIA MONEY NOT NULL,
	THANHTIEN MONEY NULL,
);
/* Object:  Table [dbo].[NHACUNGCAP]    */


 GO 
--TẠO TRIGGER UPDATE SOLUONG KHI NHAP KHO 
CREATE TRIGGER TRG_UPDATE_HANGHOA_NHAPKHO ON DBO.XUATKHO AFTER INSERT AS
BEGIN
	UPDATE DBO.HANGHOA
	SET SOLUONGSANSANG = SOLUONGSANSANG -(SELECT SOLUONG FROM inserted WHERE ID_MAHANGHOA = HANGHOA.MAHANGHOA)
	FROM DBO.HANGHOA
	JOIN inserted 
	ON HANGHOA.MAHANGHOA = inserted.ID_MAHANGHOA
END

GO
--TẠO TRIGGER UPDATE SOLUONG SAU KHI XUAT KHO
CREATE TRIGGER TRG_UPDATE_HANGHOA_XUATKHO ON DBO.NHAPKHO AFTER INSERT AS
BEGIN
	UPDATE DBO.HANGHOA
	SET SOLUONGSANSANG = SOLUONGSANSANG +(SELECT SOLUONG FROM inserted WHERE ID_MAHANGHOA = HANGHOA.MAHANGHOA)
	FROM DBO.HANGHOA
	JOIN inserted 
	ON HANGHOA.MAHANGHOA = inserted.ID_MAHANGHOA
END

GO

--INSERT THÔNG TIN VỀ QUẢN LÝ KHO 
--INSERT BẢNG HÀNG HÓA

SET IDENTITY_INSERT HANGHOA ON
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (1, N'MÁY GIẶT BALE',N'Nhật Bản' ,5000000 ,2)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (2, N'MÁY GIẶT KANTE',N'Nhật Bản' ,1000000 ,3)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (3, N'MÁY GIẶT MANE',N'Nhật Bản' ,2000000 ,4)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (4, N'MÁY GIẶT PETIT',N'Hàn Quốc' ,3000000 ,5)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (5, N'MÁY ĐIỀU HÒA RONALDO',N'Hàn Quốc' ,4000000 ,6)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (6, N'MÁY ĐIỀU HÒA BENZEMA',N'Hàn Quốc' ,6000000 ,7)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (7, N'MÁY ĐIỀU HÒA BUFFON',N'Trung Quốc' ,5000000 ,8)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (8, N'MÁY SẤY CHICHARITO',N'Trung Quốc' ,10000000 ,9)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (9, N'MÁY SƯỞI REUS',N'Việt Nam' ,1100000 ,3)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONGSANSANG]) VALUES (10, N'MÁY XAY DYBALA',N'Việt Nam' ,4500000 ,2)
SET IDENTITY_INSERT HANGHOA OFF
GO
--INSERT BẢNG NHÀ CUNG CẤP 

SET IDENTITY_INSERT NHACUNGCAP ON
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (1,N'XƯỞNG MÁY CAO CẤP TIẾN THÀNH',N'HÀ ĐÔNG-HÀ NỘI',0913313310)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (2,N'XƯỞNG MÁY CAO ĐỨC',N'ĐỐNG ĐA-Hà Nội',0913313311)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (3,N'XƯỞNG MÁY THỊNH NGUYỄN',N'HÀ NỘI',0913313312)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (4,N'XƯỞNG MÁY THẮNG ĐINH',N'HÀ NỘI',0913313313)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (5,N'XƯỞNG MÁY DÂN DỤNG VIỆT ANH',N'NINH BÌNH',0913313314)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (6,N'XƯỞNG MÁY CORONA',N'TRUNG QUỐC',0913313315)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (7,N'XƯỞNG MÁY H5N1',N'HÀN QUỐC',0913313316)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (8,N'XƯỞNG MÁY SAMSUNG',N'MỸ',0913313317)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (9,N'XƯỞNG MÁY SONY',N'BỒ ĐÀO NHA',0913313318)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (10,N'XƯỞNG MÁY TOSHIBA',N'TÂY BAN NHA',0913313319)
SET IDENTITY_INSERT NHACUNGCAP OFF
GO

--INSERT BẢNG NHẬP KHO 
SET IDENTITY_INSERT NHAPKHO ON
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(1,CAST(N'2018-05-06' AS Date),1,1, 1 , 1000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(2,CAST(N'2018-05-07' AS Date),2,2,2 , 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(3,CAST(N'2018-05-08' AS Date),3,3,3, 1000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(4,CAST(N'2018-05-09' AS Date),4,4,4, 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(5,CAST(N'2018-05-10' AS Date),5,5,5, 3000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(6,CAST(N'2018-05-11' AS Date),6,6,6, 4000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(7,CAST(N'2018-05-12' AS Date),7,7,7, 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(8,CAST(N'2018-05-13' AS Date),8,8,8, 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(9,CAST(N'2018-05-14' AS Date),9,9,9, 1000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[ID_MAHANGHOA],[ID_MANHACUNGCAP],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(10,CAST(N'2018-05-15' AS Date),10,10,10 , 3000000, NULL )
SET IDENTITY_INSERT NHAPKHO OFF
GO
--INSERT BẢNG XUẤT KHO
SET IDENTITY_INSERT XUATKHO ON
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(1,CAST(N'2019-05-06' AS Date),10, 10 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(2,CAST(N'2019-05-07' AS Date),9,9 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(3,CAST(N'2019-05-08' AS Date),8,8 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(4,CAST(N'2019-05-09' AS Date),7,7 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(5,CAST(N'2019-05-10' AS Date),6,6 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(6,CAST(N'2019-05-11' AS Date),5,5 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(7,CAST(N'2019-05-12' AS Date),4,4 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(8,CAST(N'2019-05-13' AS Date),3,3 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(9,CAST(N'2019-05-14' AS Date),2,2 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[ID_MAHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(10,CAST(N'2019-05-15' AS Date),1,1 , 1000000, NULL )
SET IDENTITY_INSERT XUATKHO OFF
GO


