USE [Quanlykho]
GO
/* Object:  Table [dbo].[KHACHHANG]    */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HANGHOA](
	[MAHANGHOA]		[int] NOT NULL,
	[TENHANGHOA]	[nvarchar](50) NULL,
	[XUATXU]		[nvarchar](50) NULL,
	[DONGIA]		[double] NULL,
	[SOLUONG]		[int] NULL,
 CONSTRAINT		[PK_HANGHOA] PRIMARY KEY CLUSTERED 
(
	[MAHANGHOA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/* Object:  Table [dbo].[NHAPKHO]    */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHAPKHO](
	[MANHAPKHO] [int] NOT NULL,
	[NGAYNHAPKHO] [date] NULL,
	[TENHANGHOA] [nvarchar](50) NULL,
	[SOLUONG] [int] NULL,
	[DONGIA] [nvarchar](50) NULL,
	[THANHTIEN] [double] NULL,
	
 CONSTRAINT [PK_NHAPKHO] PRIMARY KEY CLUSTERED 
(
	[MANHAPKHO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/* Object:  Table [dbo].[XUATKHO]    */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[XUATKHO](
	[MAXUATKHO] [int] NOT NULL,
	[NGAYXUATKHO] [date] NULL,
	[TENHANGHOA] [nvarchar](50) NULL,
	[SOLUONG] [int] NULL,
	[DONGIA] [nvarchar](50) NULL,
	[THANHTIEN] [double] NULL,

 CONSTRAINT [PK_XUATKHO] PRIMARY KEY CLUSTERED 
(
	[MAXUATKHO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/* Object:  Table [dbo].[NHACUNGCAP]    */
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHACUNGCAP](
	[MANHACUNGCAP]		[int] NOT NULL,
	[TENNHACUNGCAP]		[nvarchar](50) NULL,
	[DIACHI]			[nvarchar](50) NULL,
	[SĐT]				[int] NULL,

 CONSTRAINT		[PK_NHACUNGCAP] PRIMARY KEY CLUSTERED 
(
	[MANHACUNGCAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--INSERT THÔNG TIN VỀ QUẢN LÝ KHO 
--INSERT BẢNG HÀNG HÓA

INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (1, N'MÁY GIẶT BALE',N'Nhật Bản' ,5000000 ,2)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (2, N'MÁY GIẶT KANTE',N'Nhật Bản' ,1000000 ,3)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (3, N'MÁY GIẶT MANE',N'Nhật Bản' ,2000000 ,4)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (4, N'MÁY GIẶT PETIT',N'Hàn Quốc' ,3000000 ,5)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (5, N'MÁY ĐIỀU HÒA RONALDO',N'Hàn Quốc' ,4000000 ,6)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (6, N'MÁY ĐIỀU HÒA BENZEMA',N'Hàn Quốc' ,6000000 ,7)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (7, N'MÁY ĐIỀU HÒA BUFFON',N'Trung Quốc' ,5000000 ,8)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (8, N'MÁY SẤY CHICHARITO',N'Trung Quốc' ,10000000 ,9)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (9, N'MÁY SƯỞI REUS',N'Việt Nam' ,1100000 ,3)
INSERT [dbo].[HANGHOA] ([MAHANGHOA], [TENHANGHOA], [XUATXU], [DONGIA], [SOLUONG]) VALUES (10, N'MÁY XAY DYBALA',N'Việt Nam' ,4500000 ,2)

--INSERT BẢNG NHẬP KHO 
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(1,CAST(N'2018-05-06' AS Date),N'MÁY HÚT BỤI BECKER', 1 , 1000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(2,CAST(N'2018-05-07' AS Date), N'MÁY SẤY TÓC KIMMICH',2 , 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(3,CAST(N'2018-05-08' AS Date), N'MÁY XAY GIGGS',3, 1000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(4,CAST(N'2018-05-09' AS Date), N'MÁY ĐIỀU HÒA KAKA',4, 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(5,CAST(N'2018-05-10' AS Date), N'MÁY LẠNH ROONEY',5, 3000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(6,CAST(N'2018-05-11' AS Date), N'MÁY LÀM SỮA CHUA POGBA',6, 4000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(7,CAST(N'2018-05-12' AS Date), N'MÁY SƯỞI ANDERSON',7, 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(8,CAST(N'2018-05-13' AS Date), N'MÁY LỌC KHÔNG KHÍ FERNANDED',8, 2000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(9,CAST(N'2018-05-14' AS Date), N'MÁY RỦA BÁT HULK',9, 1000000, NULL )
INSERT[dbo].[NHAPKHO] ([MANHAPKHO],[NGAYNHAPKHO],[TENHANGHOA],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(10,CAST(N'2018-05-15' AS Date), N'MÁY ĐÁNH TRỨNG SON',10 , 3000000, NULL )

--INSERT BẢNG XUẤT KHO
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(1,CAST(N'2019-05-06' AS Date),N'MÁY HÚT BỤI BECKER', 10 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(2,CAST(N'2019-05-07' AS Date), N'MÁY SẤY HOA QUẢ KIMMICH',9 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(3,CAST(N'2019-05-08' AS Date), N'MÁY LÀ COUTINHO',8 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(4,CAST(N'2019-05-09' AS Date), N'MÁY HÚT BỤI NEYMAR',7 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(5,CAST(N'2019-05-10' AS Date), N'MÁY MASSAGE STONE',6 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(6,CAST(N'2019-05-11' AS Date), N'MÁY LỌC NƯỚC MODRIC',5 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(7,CAST(N'2019-05-12' AS Date), N'MÁY XAY BECKHAM',4 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(8,CAST(N'2019-05-13' AS Date), N'MÁY TÍNH FORLAN',3 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(9,CAST(N'2019-05-14' AS Date), N'MÁY ĐIỆN THOẠI HENRY',2 , 1000000, NULL )
INSERT[dbo].[XUATKHO] ([MAXUATKHO],[NGAYXUATKHO],[SOLUONG],[DONGIA],[THANHTIEN]) VALUES(10,CAST(N'2019-05-15' AS Date), N'MÁY TÍNH BẢNG ZIDANE',1 , 1000000, NULL )

--INSERT BẢNG NHÀ CUNG CẤP 
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (1,N'XƯỞNG MÁY CAO CẤP TIẾN THÀNH',N'HÀ ĐÔNG-HÀ NỘI',0913313310)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (2,N'XƯỞNG MÁY CAO ĐỨC',N'ĐỐNG ĐA-Hà Nội',0913313311)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (3,N'XƯỞNG MÁY THỊNH NGUYỄN',N'HÀ NỘI',0913313312)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (4,N'XƯỞNG MÁY THẮNG ĐINH',N'HÀ NỘI',0913313313)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (5,N'XƯỞNG MÁY DÂN DỤNG VIỆT ANH',N'NINH BÌNH',0913313314)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (6,N'XƯỞNG MÁY CORONA',N'TRUNG QUỐC',0913313315)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (7,N'XƯỞNG MÁY H5N1',N'HÀN QUỐC',0913313316)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (8,N'XƯỞNG MÁY SAMSUNG',N'MỸ',0913313317)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (9,N'XƯỞNG MÁY SONY',N'BỒ ĐÀO NHA',0913313318)
INSERT[dbo].[NHACUNGCAP] ([MANHACUNGCAP],[TENNHACUNGCAP],[DIACHI],[SĐT]) VALUES (10,N'XƯỞNG MÁY TOSHIBA',N'TÂY BAN NHA',0913313319)




